---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Panzerbüchse-Blackrock.
--- DateTime: 09-Apr-22 13:27
---
---
local AddonName, PrivateVariables = ...;

PrivateVariables.Data = {}
local DungeonAbbreviations = {
    [375] = "mots",
    [376] = "nw",
    [377] = "dos",
    [378] = "hoa",
    [379] = "pf",
    [380] = "sd",
    [381] = "soa",
    [382] = "top",
    [391] = "strt",
    [392] = "gmbt"
}
PrivateVariables.Data.DungeonAbbreviations = {
}
for id, abbr in pairs(DungeonAbbreviations) do
    PrivateVariables.Data.DungeonAbbreviations[id] = abbr
    PrivateVariables.Data.DungeonAbbreviations[abbr] = id
end
PrivateVariables.Data.WeeklyAffixAbbreviations = {
    Tyrannical = "Tyrannical",
    Fortified = "Fortified"
}
for abbr, name in pairs(PrivateVariables.Data.WeeklyAffixAbbreviations) do
    PrivateVariables.Data.WeeklyAffixAbbreviations[strsub(abbr, 1, 1)] = name
    PrivateVariables.Data.WeeklyAffixAbbreviations[strsub(abbr, 1, 3)] = name
end
--- computed base scores for key level 1 to 10 based on affix activation at 4,7,10
PrivateVariables.Data.DungeonBaseScores = { 0, 40, 45, 55, 60, 65, 75, 80, 85, 100 };

PrivateVariables.Data.TimerConstants = {
    ---@type number bonus and malus are capped at 40% faster or slower than par time
    Threshold = 0.4,
    ---@type number maximum bonus/malus points for being faster/slower than the par time
    MaxModifier = 5,
    ---@type number maximum bonus/malus points for being faster/slower than the par time
    KeyDepletionMalus = 5,
}
