---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Panzerbüchse-Blackrock.
--- DateTime: 09-Apr-22 16:10
---
local RioHelper = LibStub("AceAddon-3.0"):GetAddon("RioHelper")

local DungeonAbbreviations = RioHelper.Data.DungeonAbbreviations
local WeeklyAffixAbbreviations = RioHelper.Data.WeeklyAffixAbbreviations

local RiohFunctions = RioHelper.Functions
local coerce = RioHelper.Functions.coerce


function RioHelper:OnInitialize()
    print("RIO Helper loaded")
end
SLASH_RIO_HELPER1, SLASH_RIO_HELPER2 = '/rioh', "/rh"
function SlashCmdList.RIO_HELPER(msg, editbox)
    -- pattern matching that skips leading whitespace and whitespace between cmd and args
    -- any whitespace at end of args is retained
    local foo, bar, dungeonAbbreviationPar, keyLevelPar, weeklyAffixPar = string.find(msg, "(%w+)%s+(%d+)%s+(%w+)")
    RioHelper:computeScoreBonus(dungeonAbbreviationPar, keyLevelPar, weeklyAffixPar)
end

function RioHelper:computeScoreBonus(dungeonAbbreviationPar, keyLevelPar, weeklyAffixPar)
    if not dungeonAbbreviationPar or not keyLevelPar or not weeklyAffixPar then
        RioHelper:Print("Unknown parameters for /rh: \""..msg.."\"")
        RioHelper:Print("Usage: /rh dungeonAbbreviation keyLevel weeklyAffix")
        return
    end

    local dungeonId = DungeonAbbreviations[dungeonAbbreviationPar];
    local weeklyAffix = WeeklyAffixAbbreviations[weeklyAffixPar]
    local blizzardScores = {
        Tyrannical = { score = 0, baseScore = 0, timeBonus = 0, parTimePercentage = 0 },
        Fortified = { score = 0, baseScore = 0, timeBonus = 0, parTimePercentage = 0 }
    }
    local name, id, parTime = C_ChallengeMode.GetMapUIInfo(dungeonId)
    local blizzardDungeonAffixScoreData, blizzardDungeonTotalScore = C_MythicPlus.GetSeasonBestAffixScoreInfoForMap(dungeonId)
    blizzardDungeonTotalScore = coerce(blizzardDungeonTotalScore, 0)
    local blizzardCurrentSeasonTotalScore = C_ChallengeMode.GetOverallDungeonScore()

    blizzardScores[weeklyAffix] = RiohFunctions.computeScores(dungeonId, keyLevelPar, parTime)
    if (blizzardDungeonAffixScoreData ~= nil) then
        for _, weeklyAffixData in pairs(blizzardDungeonAffixScoreData) do
            if (weeklyAffixData.name ~= weeklyAffix) then
                blizzardScores[weeklyAffixData.name] = RiohFunctions.computeScores(dungeonId, weeklyAffixData.level, weeklyAffixData.durationSec)
            end
        end
    end
    local newSum = RiohFunctions.computeAffixScoreSum(blizzardScores.Tyrannical.score, blizzardScores.Fortified.score)
    local bonusScore = newSum - blizzardDungeonTotalScore
    RioHelper:Print(RiohFunctions.formatNumber(bonusScore, 1) ..
            " from " .. blizzardDungeonTotalScore .. " to " ..
            RiohFunctions.formatNumber(newSum, 1, true)..
            " New total score: "..RiohFunctions.formatNumber((blizzardCurrentSeasonTotalScore + bonusScore), 1, true)
    )
end